services:
  - type: web
    name: flask-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: "gunicorn run:app"
